# config.default.toml
app_name = "BioPyAssistant"
app_description = "BioPyAssistant is a teaching assistant for Patrick Fuchs and Pierre Poulain's Python programming course for biologists."
app_version = "2.0"
css_path = "assets/style.css"
course_yaml_path = "data/chapters_and_levels.yaml"

[llm]
llm_model_name= "gpt-4o"
provider_llm_name = "openai"
vector_database_path = "chroma_db"
embeddings_model_name = "text-embedding-3-large"
provider_embeddings_name = "openai"