name: biopyassistantenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - python-dotenv # For environment variables
  # Linters and formaters
  - pycodestyle
  - pydocstyle
  - pylint
  - black
  - ruff
  - mypy
  # LLM tools
  - chromadb # Vector storage
  - openai # For embeddings and models
  - tiktoken # For tokenization
  - langchain # For language processing
  - langchain-openai
  - langchain-mistralai
  - langchain-groq
  - langchain-core
  - langchain-community
  - langchain-text-splitters
  # Logging
  - loguru
  # IU : Web app
  - streamlit
  - gradio
  # Evaluation
  - ragas

